/*Formulario Principal Veterinaria */
package View;

/**
 *
 * @author carlos
 */
import Controller.ClsMainMenu;



public class frmMainMenu extends javax.swing.JFrame {
    //----------mis variables---------------    
    private final ClsMainMenu mClsMainMenu= new ClsMainMenu();

    //----------mis funciones---------------
    private void init(){
        //Obtener datos de la base de datos
            //usuarios                                                
            //---->Dao.init("Veterinaria");//inicializar la conexión con la base de datos
            
            /*
            ArrayList<ArrayList<String>> A;            
                        // columnas  /  tabla(s)  / condición / llaves foráneas para crear condición
            A=Dao.select("User,Password", "Usuario",null);
                Market.createUsuarios(A);
            A=Dao.select("Codigo_Producto,Nombre_Producto,Precio_costo,Precio_venta","Productos",null);
                Market.createProductos(A);
            A=Dao.select("Nombre,RUC", "Distribuidores", null);
                Market.createDistribuidores(A);               
            A=Dao.select("Nombre_Persona,DNI,Telefono_Persona,Direccion_Persona", "Clientes,Persona", "idPersona,idPersona", null);
                Market.createClientes(A);
        
            */    
                
                
        //Crear Formularios
                
                /*frms.add(new frmLogin());
                frms.get(0).show();frms.get(0).requestFocusInWindow();
                frms.add(new frmListaProductos());
                frms.add(new frmBuscarCliente());
                frms.add(new frmListaClientes());
                frms.add(new frmVerOperaciones());
                frms.add(new frmNuevaVenta());*/
                
                
              
         
        //objeto timer para evaluación constante de cambios en el sistema
        /*TimerTask task=new TimerTask(){
                        public void run(){
                            if(frmMainMenu._ingresar)
                                frmMainMenu.this.enable(true);
                        }
                    };
        Timer timer=new Timer();
        timer.scheduleAtFixedRate(task, 0, 100);*/
        
    }    
    /*Entrar al programa
    public static void ingresar(boolean entrar){
        frmMainMenu._ingresar=entrar;
        //ocultar el login
        if(entrar)
           frmMainMenu.frms.get(0).hide();       
        else
            JOptionPane.showMessageDialog(null, "Datos ingresados incorrectos.");
    }*/
    /**
     * Creates new form frmSolaris
     */
    public frmMainMenu() {
        initComponents();
        //centrar formulario
        frmMainMenu.this.setLocationRelativeTo(null);        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mUsuario = new javax.swing.JMenu();
        mUsuarioConfigurar = new javax.swing.JMenu();
        mUsuarioSalir = new javax.swing.JMenu();
        mClientes = new javax.swing.JMenu();
        smMantenerCliente = new javax.swing.JMenuItem();
        smBuscarCliente = new javax.swing.JMenuItem();
        mMascota = new javax.swing.JMenu();
        smMantenerMascota = new javax.swing.JMenuItem();
        smBuscarMascota = new javax.swing.JMenuItem();
        smRegistrar = new javax.swing.JMenuItem();
        smBuscarHC = new javax.swing.JMenuItem();
        mCitaMedica = new javax.swing.JMenu();
        smRegistrarCitaMedica = new javax.swing.JMenuItem();
        mServicio = new javax.swing.JMenu();
        smGenerarConceptoBoletaVenta = new javax.swing.JMenuItem();
        mInfoSoporte = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        mInfoAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Veterinaria");
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/main_background_veterinaria.png"))); // NOI18N
        jLabel1.setAlignmentX(0.5F);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N

        mUsuario.setText("Usuario");

        mUsuarioConfigurar.setText("Confirgurar");
        mUsuario.add(mUsuarioConfigurar);

        mUsuarioSalir.setText("Salir");
        mUsuario.add(mUsuarioSalir);

        jMenuBar1.add(mUsuario);

        mClientes.setText("Clientes");

        smMantenerCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        smMantenerCliente.setText("Mantener Cliente");
        smMantenerCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smMantenerClienteActionPerformed(evt);
            }
        });
        mClientes.add(smMantenerCliente);

        smBuscarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        smBuscarCliente.setText("Buscar Cliente");
        smBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smBuscarClienteActionPerformed(evt);
            }
        });
        mClientes.add(smBuscarCliente);

        jMenuBar1.add(mClientes);

        mMascota.setText("Mascota");

        smMantenerMascota.setText("Mantener Mascota");
        smMantenerMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smMantenerMascotaActionPerformed(evt);
            }
        });
        mMascota.add(smMantenerMascota);

        smBuscarMascota.setText("Buscar Mascota");
        smBuscarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smBuscarMascotaActionPerformed(evt);
            }
        });
        mMascota.add(smBuscarMascota);

        smRegistrar.setText("Registrar Historia Clínica");
        smRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smRegistrarActionPerformed(evt);
            }
        });
        mMascota.add(smRegistrar);

        smBuscarHC.setText("Buscar Historia Clínica");
        smBuscarHC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smBuscarHCActionPerformed(evt);
            }
        });
        mMascota.add(smBuscarHC);

        jMenuBar1.add(mMascota);

        mCitaMedica.setText("Cita Médica");

        smRegistrarCitaMedica.setText("Registrar Cita Médica");
        smRegistrarCitaMedica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smRegistrarCitaMedicaActionPerformed(evt);
            }
        });
        mCitaMedica.add(smRegistrarCitaMedica);

        jMenuBar1.add(mCitaMedica);

        mServicio.setText("Servicio");

        smGenerarConceptoBoletaVenta.setText("Generar Concepto de Boleta Venta");
        smGenerarConceptoBoletaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smGenerarConceptoBoletaVentaActionPerformed(evt);
            }
        });
        mServicio.add(smGenerarConceptoBoletaVenta);

        jMenuBar1.add(mServicio);

        mInfoSoporte.setText("Información");

        jMenu1.setText("Soporte Técnico");
        mInfoSoporte.add(jMenu1);

        mInfoAyuda.setText("Ayuda");
        mInfoSoporte.add(mInfoAyuda);

        jMenuBar1.add(mInfoSoporte);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smMantenerClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smMantenerClienteActionPerformed
        mClsMainMenu.invocar("Mantener Cliente");
        //System.out.print("abriendo mantener cliente");        // TODO add your handling code here:
    }//GEN-LAST:event_smMantenerClienteActionPerformed

    private void smBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smBuscarClienteActionPerformed
        mClsMainMenu.invocar("Buscar Cliente");
    }//GEN-LAST:event_smBuscarClienteActionPerformed

    private void smMantenerMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smMantenerMascotaActionPerformed
        mClsMainMenu.invocar("Mantener Mascota"); 
    }//GEN-LAST:event_smMantenerMascotaActionPerformed

    private void smBuscarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smBuscarMascotaActionPerformed
       mClsMainMenu.invocar("Buscar Mascota");
    }//GEN-LAST:event_smBuscarMascotaActionPerformed

    private void smGenerarConceptoBoletaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smGenerarConceptoBoletaVentaActionPerformed
        mClsMainMenu.invocar("Generar Concepto de boleta de venta");
    }//GEN-LAST:event_smGenerarConceptoBoletaVentaActionPerformed

    private void smRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smRegistrarActionPerformed
        mClsMainMenu.invocar("Registrar Historial Clinico");
    }//GEN-LAST:event_smRegistrarActionPerformed

    private void smRegistrarCitaMedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smRegistrarCitaMedicaActionPerformed
        mClsMainMenu.invocar("Registrar Cita Médica");
    }//GEN-LAST:event_smRegistrarCitaMedicaActionPerformed

    private void smBuscarHCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smBuscarHCActionPerformed
        mClsMainMenu.invocar("Buscar Historia Clínica");
    }//GEN-LAST:event_smBuscarHCActionPerformed

        
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMainMenu().setVisible(true);
                
                
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mCitaMedica;
    private javax.swing.JMenu mClientes;
    private javax.swing.JMenu mInfoAyuda;
    private javax.swing.JMenu mInfoSoporte;
    private javax.swing.JMenu mMascota;
    private javax.swing.JMenu mServicio;
    private javax.swing.JMenu mUsuario;
    private javax.swing.JMenu mUsuarioConfigurar;
    private javax.swing.JMenu mUsuarioSalir;
    private javax.swing.JMenuItem smBuscarCliente;
    private javax.swing.JMenuItem smBuscarHC;
    private javax.swing.JMenuItem smBuscarMascota;
    private javax.swing.JMenuItem smGenerarConceptoBoletaVenta;
    private javax.swing.JMenuItem smMantenerCliente;
    private javax.swing.JMenuItem smMantenerMascota;
    private javax.swing.JMenuItem smRegistrar;
    private javax.swing.JMenuItem smRegistrarCitaMedica;
    // End of variables declaration//GEN-END:variables
}
